<?php

/*
 * Implement Hook_Cron();
 */

function node_db_extension_cron() {
    inspectAddHoteles();
    inspectAddReservas();
    drupal_flush_all_caches();
}

/*
 * Implements custom functions
 */

function getHotelFromDrupal() {
    $type = 'hoteles';
    $query_nid = "SELECT count(nid) count FROM node WHERE type LIKE '%s'";
    $result_start = db_query($query_nid, $type);
    $cantidad = 0;
    
    while ($row = db_fetch_object($result_start)) {
        $cantidad = (int) ($row->count);
    }

    return $cantidad;
}

function getReservaFromDrupal() {
    $type = 'reservas';
    $query_nid = "SELECT count(nid) count FROM node WHERE type LIKE '%s'";
    $result_start = db_query($query_nid, $type);
    $cantidad = 0;
    
    while ($row = db_fetch_object($result_start)) {
        $cantidad = (int) ($row->count);
    }

    return $cantidad;
}

function getHotelFromExternal() {
    db_set_active('external');
    $result = db_query("SELECT count(hotel_id) count FROM Hoteles");
    db_set_active('default');
    
    $cantidad = 0;
    
    while ($row = db_fetch_object($result)) {
        $cantidad = (int) ($row->count);
    }
    
    return $cantidad;
}

function getReservaFromExternal() {
    db_set_active('external');
    $result = db_query("SELECT count(reserva_id) count FROM Reservas");
    db_set_active('default');
    
    $cantidad = 0;
    
    while ($row = db_fetch_object($result)) {
        $cantidad = (int) ($row->count);
    }
    
    return $cantidad;
}

function getNidNewsReserves($reserva) {
    db_set_active('external');
    $nombres = db_query("SELECT nombre FROM Hoteles h JOIN Reservas r ON h.hotel_id = r.hotel_id WHERE r.cliente LIKE '$reserva'");
    db_set_active('default');
    
    while ($row = db_fetch_object($nombres)) {
        $query = "SELECT nid FROM node WHERE type LIKE '%s' AND title LIKE '%s'";
        $type = "hoteles";
        $title = $row->nombre;
        $nid_ref = db_query($query,$type,$title);
    }
    
    while ($row_1 = db_fetch_object($nid_ref)) {
        $nid = (int) ($row_1->nid);
    }
    
    return $nid;
}

function inspectAddHoteles() {
    global $user;
    
    $cantidad_actual_hotel = getHotelFromDrupal();
    $cantidad_final_hotel = getHotelFromExternal();
    
    /* Verifica si hay nuevos registros */
    
    if ($cantidad_actual_hotel < $cantidad_final_hotel) {
        db_set_active('external');
        
        $cant_add = $cantidad_final_hotel - $cantidad_actual_hotel;
        $query = "SELECT * FROM Hoteles ORDER BY hotel_id DESC LIMIT %d";
        $additional = db_query($query, $cant_add);
        
        db_set_active('default');
        
        while ($row = db_fetch_object($additional)) {
            $node = new stdClass();
            
            $node->uid = $user->uid;
            $node->type = 'hoteles';
            $node->title = $row->nombre;
            $node->body = $row->direccion;
            $node->created = time();
            $node->changed = $node->created;
            $node->promote = 0;
            $node->sticky = 0;
            $node->format = 2;
            $node->status = 1; 
            $node->language = 'es';
            $node->field_numero[0]['value'] = $row->telefono;
            $file_path = $row->imagen;
            $target_path = "sites/default/files/";

            $node->field_imagen[0] = field_file_save_file($file_path, array(), $target_path);
            //$nodo_1 = node_submit($node);
            //node_save($nodo_1);
            node_save($node);
        }
    }
}

function inspectAddReservas() {
    global $user;
    
    $cantidad_actual_reserva = getReservaFromDrupal();
    $cantidad_final_reserva = getReservaFromExternal();
    
    if ($cantidad_actual_reserva < $cantidad_final_reserva) {
        db_set_active('external');
        
        $cant_add = $cantidad_final_reserva - $cantidad_actual_reserva;
        $query = "SELECT * FROM Reservas ORDER BY reserva_id DESC LIMIT %d";
        $additional = db_query($query, $cant_add);
        
        db_set_active('default');
        
        while ($row = db_fetch_object($additional)) {
            $node = new stdClass();
            
            $nid = getNidNewsReserves($row->cliente);
            
            $node->uid = $user->uid;
            $node->type = 'reservas';
            $node->title = $row->cliente;
            $node->body = "Some Text";
            $node->created = time();
            $node->changed = $node->created;
            $node->promote = 0;
            $node->sticky = 0;
            $node->format = 2;
            $node->status = 1; 
            $node->language = 'es';
            $node->field_numhotel[0]['nid'] = $nid;
            $node->field_datestart[0]['value'] = $row->fecha_inicio;
            $node->field_datend[0]['value'] = $row->fecha_fin;
            $node->field_numreserv[0]['value'] = $row->reserva_id;

            //$nodo_2 = node_submit($node);
            //node_save($nodo_2);
            node_save($node);
        }
    }
}