<?php
/**
* @file
* This is my first module :D
* Implementation of hook_menu()
*/
function block_test_help($path, $arg){
	switch($path){
	 case 'admin/menu/block':
	   return '<p>'.t('this is a help for the block').'</p>';
	 case 'user/%':
	   return '<p>'.t('this is a help').'</p>';
	}
}

/**
* @file
* This is my first module :D
* Implementation of hook_menu()
*/
function block_test_block($op='list', $delta=1, $edit=array()){
 switch($op){
  case 'list':
	$blocks[0]['info'] = t("Nodos no publicados");
	$blocks[0]['cache'] = BLOCK_NO_CACHE; //Esto me indica que el bloque no aplicara CACHE para obtener los datos.
	$blocks[1]['info'] = t('Todos los usuarios registrados');
	return $blocks;
  case 'configure':
      if($delta==0){
	$form['block_test_num_nodes'] = array(
		'#type' => 'textfield',
		'#title' => t('Cantidad de nodos a mostrar'),
		'#default_value' => variable_get('block_test_num_nodes', 5),
	);
       }
	return $form;
  case 'save':
	if($delta==0){
	variable_set('block_test_num_nodes', (int)$edit['block_test_num_nodes']);
	break;
	}
  case 'view':
	if($delta==0){
	$num_nodes = variable_get('block_test_num_nodes', 5);
	$result = db_query_range("SELECT * FROM {node} WHERE status = %d ORDER BY changed desc", NODE_NOT_PUBLISHED, 0, $num_nodes); //Me saca del query, una cantidad definida de rows
	$items = array();
	while($node = db_fetch_object($result)){
	   $items[] = l($node->title, drupal_get_path_alias('node/'. $node->nid));
	}
	$block['subject']= t('Nodos no publicados');
	$block['content']= theme('item_list', $items);
	}else{
	 $result = db_query_range("SELECT * FROM {users} WHERE status = %d ORDER BY created desc", 1, 0, 5);
	 $items = array();
	 while($user = db_fetch_object($result)){
	   $items[] = l($user->name, 'user/'.$user->uid);
	 }
	 $block['subject'] = t('Users List');
	 $block['content'] = theme('item_list', $items);
	}
	return $block;
 }
}
