<?
/**
* @file
* Freddy module FORM API workshop
* This module shows a menu
*
*/



/**
* Implementation of hook_menu
*/

function example_form_menu(){
$items['example_forms/form1']=array(
	'title'=>t('Example Form 1'),
	'page callback'=>'drupal_get_form',
	'page arguments'=>array('example_forms_form1'),//argument for the drupal_get_form function
	'access callback'=>TRUE,
	'description'=>t('Example Form 1'),
	'type'=>MENU_CALLBACK
);

return $items;

}


/**
* Page's callback
*/

function example_forms_form1($form_state){
$form['description']=array(
	'#type'=>'item',
	'#title'=>t('A simple form'),
);

$form['full_name']=array(
	'#type'=>'textfield',
	'#title'=>t('Full Name'),
	
);

$form['info']=array(
	'#value'=>'Mi perro murio',

);

$form['check']=array(
	'#type'=>'checkbox',
	'#title'=>'dame check',
);


$form['checks']=array(
	'#type'=>'checkboxes',
	'#title'=>'Choose',
	'#default_value'=> array('a'),
	'#options'=>array('a'=>'tengo mi check!',
			  'b'=>'kiero un check',
			  'c'=>'nooo, io kieroo'),
	'#description'=>t('choose any option you want'),
	'#attributes'=>array('class' => 'mi-form'),
);


$form['submit']=array(
	'#type'=>'submit',
	'#value'=>'guardar',
	
);

$form['preview']=array(
	'#type'=>'button',
	'#value'=>'previsualizar',
	'#weight'=>4,
	
);

return $form;
}

function example_forms_form1_validate($form, $form_state){

	$nombre=$form_state['values']['full_name'];
	
	if(strcmp($nombre,'leila')==0){
	
	drupal_set_message("NOOOOO");
	}else{
	drupal_set_message("xD");
	form_set_error("mal");
	}

}

function example_forms_form1_submit($form,$form_state){
	db_query("Insert into {example1} (author) values ('%s')",$form_state['values']['full_name']);

	drupal_set_message("dizq se grabo todo");
}

