<?php

/*
 * Implementation of HOOK_MENU
 */

function send_data_menu() {
    $items['send_data'] = array(
        'title' => t('Envio de datos'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('send_data_form'),
        'access callback' => TRUE,
        'description' => t('Puedes ingresar los datos aqui y con el boton enviar los datos'),
        'type' => MENU_CALLBACK
    ); 
    
    return $items;
}

/*
 * Implementation of HOOK_FORM
 */

function send_data_form($form_state) {
    $form['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Pon tu nombre completo'),
        '#description' => t('Inserta el nombre el cual sera enviado.')
    ); 
    
    $form['email'] = array(
        '#type' => 'textfield',
        '#title' => t('Pon tu correo electronico'),
        '#description' => t('Inserta el apellido el cual sera enviado.')
    ); 
    
    $form['phone'] = array(
        '#type' => 'textfield',
        '#title' => t('Pon tu telefono fijo o celular'),
        '#description' => t('Inserta el telefono el cual sera enviado.')
    );
    
    $form['event_id'] = array(
        '#type' => 'textfield',
        '#title' => t('El n° de hotel'),
        '#description' => t('Es el n° del hotel.'),
        '#default_value' => $_GET['id']
    );
    
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Enviar'
    );

    return $form;
}

/*
 * Implementation of HOOK_FORM_VALIDATE
 */

function send_data_form_validate($form, &$form_state) {
    $name = $form_state['values']['name'];
    $email = $form_state['values']['email'];
    $phone = $form_state['values']['phone'];
    $event_id = (int)($form_state['values']['event_id']);
    
    IF(is_numeric($name)){
        form_set_error($name, "El Nombre debe ser válido");
    }
    
    IF(!is_numeric($phone)){
        form_set_error($phone, "El telefono debe ser válido");
    }
    
    IF(!is_numeric($event_id)){
        form_set_error($event_id, "El id del evento debe ser un numero");
    }
    
    IF(is_numeric($email)){
        form_set_error($email, "El email debe ser válido");
    }
    
    IF(strpos($email, "@") == FALSE || strpos($email, ".com") == FALSE){
        form_set_error($email, "El email debe ser válido");
    }
}

/*
 * Implementation of HOOK_FORM_SUBMIT
 */

function send_data_form_submit($form, &$form_state) {
    
    $name = $form_state['values']['name'];
    $email = $form_state['values']['email'];
    $phone = $form_state['values']['phone'];
    $event_id = (int)($form_state['values']['event_id']);
    
    $data_attendee = array( 'attendee' => array(
            'name' => $name,
            'email' => $email,
            'phone' => $phone,
            'event_id' => $event_id
        )
    );
    
    $data_user = array( 'user' => array(
            'email' => 'eduardo.cabrera@tektonlabs.com',
            'password' => 123456
        )
    );
    
    $url_login = 'http://173.204.41.98/eventmobile/users/sign_in';
    $url_target = 'http://173.204.41.98/eventmobile/attendee_management/attendee';
    
    $ch = curl_init();
    
    /*   
    if(preg_match('#Location: (.*)#', $result, $r)){
           $url_redirect = trim($r[1]);
    }
    */
    
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, TRUE);
    curl_setopt($ch, CURLOPT_URL, $url_login);
    curl_setopt($ch, CURLOPT_POST, TRUE);
    curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($data_user));
    $result = curl_exec($ch);
    $http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    
    curl_setopt($ch, CURLOPT_URL, $url_target);
    curl_setopt($ch, CURLOPT_POST, TRUE);
    curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($data_attendee));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
    curl_setopt($ch, CURLOPT_FAILONERROR, TRUE);
    curl_setopt($ch, CURLOPT_HEADER, $header);
    $result = curl_exec($ch);
    $http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
}